apiVersion: v1
kind: Service
metadata:
  name: futurekawa-api-service
  namespace: futurekawa-app
spec:
  type: ClusterIP
  selector:
    app: futurekawa-api
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001