name: CI/CD Pipeline

on:
  push:
    branches: ["main", "test_moua"]
  pull_request:
    branches: ["main", "test_moua"]
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: shared-runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies and run tests
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          python -m pytest -q

  build-and-push:
    runs-on: shared-runners
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Push with Kaniko
        uses: aevea/action-kaniko@v0.10.0
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
          tag: latest,sha-${{ github.sha }}
          cache: true